### ISSUE TITLE
Something went wrong

### ISSUE THREAD

**Issue by GRIM2D** [mladenplavsic/css-ripple-effect#1]
![gif](https://cloud.githubusercontent.com/assets/6705445/18310741/b0715d32-7519-11e6-9f1a-0ed681f2acec.gif)
```
Chrome on OSX
Version 52.0.2743.116 (64-bit)
```

**Comment by mladenplavsic** [comment]
Fixed with 3face2f288753cc5ce952b977898cbc10550cd2b
