### ISSUE TITLE
Doesn't work with Bootstrap v4 dropdown menu

### ISSUE THREAD

**Issue by badamsdev** [mladenplavsic/css-ripple-effect#18]
Adding ripple to the dropdown link, makes the caret-down disappear and the ripple is not centred vertically.

https://jsfiddle.net/aq9Laaew/197449/

Chrome, Firefox and Edge 0n Windows...

**Comment by mladenplavsic** [comment]
As ripple is created in CSS, it uses `:after` pseudo element to create the effect. In your example the same pseudo element is used to show the caret, and it gets overridden. Changing either one to `:before` might solve it.
