### ISSUE TITLE
Click functionality breaks when used on button with font-awesome inside

### ISSUE THREAD

**Issue by tusharshuklaa** [mladenplavsic/css-ripple-effect#6]
May be this is not an issue and something out of my own error but i'm unable to figure it out and hence would like to seek your help for same.

When trying to implement the code in ripple.min.css on a button, following issues occur for reasons unknown to me:
1. Click stops working! This is the button code:
<button type="button"  onclick="action()"  class="customBtn ripple"><i class="fa fa-chevron-left"></i></button>

2. It blinks rather than 'ripple'

This is what '.customBtn ' looks like:
.customBtn  {
    position: fixed;
    top: 50%;
    font-size: 8em;
    background-color: transparent;
    color: grey;
    outline: 0;
    border: none;
}

This is what i've copied in my CSS (SCSS) from your code:
.ripple {
  position: relative;
  overflow: hidden;

  &:after {
    content: "";
    display: block;
    position: absolute;
    width: 100%;
    height: 100%;
    top: 0;
    left: 0;
    pointer-events: none;
    background-image: radial-gradient(circle, #000 10%, transparent 10.01%);
    background-repeat: no-repeat;
    background-position: 50%;
    transform: scale(10,10);
    opacity: 0;
    transition: transform .5s, opacity 1s;
  }

  &:active, &:after {
    transform: scale(0,0);
    opacity: .2;
    transition: 0s;
  }
}

What is wrong in this?

**Comment by mladenplavsic** [comment]
Take a look here, it seems like it's working https://jsfiddle.net/mladenplavsic/Lt35a39f/1/

I have commented out `background` and `color` from your `.customBtn` to make the button visible.

Have you solved this problem, @tusharshuklaa ?

**Comment by tusharshuklaa** [comment]
@mladenplavsic I checked your fiddle and even changed it as per my needs and it worked well. I guess there is something else bugging the button in my case. Thanks for your response.
